/*
 * Script de población de datos básicos
 */

INSERT INTO CLIENTE(NOMCLIENTE)VALUES('CONSALUD');
INSERT INTO CLIENTE(NOMCLIENTE)VALUES('BANCO BICE');
INSERT INTO CLIENTE(NOMCLIENTE)VALUES('BANCO FABALELLA');
INSERT INTO CLIENTE(NOMCLIENTE)VALUES('MINTLAB');
INSERT INTO CLIENTE(NOMCLIENTE)VALUES('GESINTEL');
INSERT INTO CLIENTE(NOMCLIENTE)VALUES('CARDIF');

INSERT INTO ROL(NOMROL) VALUES('JEFE DE PROYECTO');
INSERT INTO ROL(NOMROL) VALUES('GERENTE DE PROYECTO');
INSERT INTO ROL(NOMROL) VALUES('LIDER DE PROYECTO');
INSERT INTO ROL(NOMROL) VALUES('ANALISTA');
INSERT INTO ROL(NOMROL) VALUES('DESARROLLADOR');
INSERT INTO ROL(NOMROL) VALUES('ARQUITECTO');
INSERT INTO ROL(NOMROL) VALUES('ARQUITECTO DE SOFTWARE');
INSERT INTO ROL(NOMROL) VALUES('ARQUITECTO DE INFRAESTRUCTURA');
INSERT INTO ROL(NOMROL) VALUES('ARQUITECTO DE BASES DE DATOS');

INSERT INTO ETAPA(NOMETAPA) VALUES('ANALISIS');
INSERT INTO ETAPA(NOMETAPA) VALUES('DISEÑO');
INSERT INTO ETAPA(NOMETAPA) VALUES('DESARROLLO');
INSERT INTO ETAPA(NOMETAPA) VALUES('CERTIFICACION');
INSERT INTO ETAPA(NOMETAPA) VALUES('PRODUCCION');

INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Jorge', 'Silva', 'Borda', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Lorena', 'González', 'Tejería', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Hugo', 'Mercado', 'Collao', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Sandra', 'López', 'Molinés', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Claudio', 'Rubilar', 'Moscoso', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Pedro', 'Bouyer', 'Arancibia', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Sergio', 'Moraga', 'Millas', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Daliamni', 'Guzman', null, 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Javier', 'Nuñez', 'Toledo', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Osciel', 'Solar', 'Maldonado', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Giovanna', 'Vaccaris', 'Calderón', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Irene', 'Riera', 'Aldana', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Antonio', 'Marreno', null, 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Nioka', 'Moreno', 'Gutiérrez', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Sergio', 'Moraga', 'Millas', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Carlos Alejandro', 'Tejería', 'Salomone', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Omar', 'Demaría', null, 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Jorge', 'Carmona', 'Castro', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Nicolás', 'Castillo', null, 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Pedro Fabián', 'Bustos', 'Jorquera', 0, 0);
INSERT INTO RECURSO(NOMBRES, APPATERNO, APMATERNO, COSTO, COSTOUSO) VALUES('Mario', 'Ibarra', null, 0, 0);