/*
 * Script de creación de tablas
 */

CREATE TABLE ROL(
	IDROL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMROL VARCHAR(400) NOT NULL
);

CREATE TABLE ETAPA(
	IDETAPA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMETAPA VARCHAR(1024) NOT NULL
);

CREATE TABLE CLIENTE(
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMCLIENTE VARCHAR(1024) NOT NULL
);

CREATE TABLE RECURSO(
	IDRECURSO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	RUTRECURSO VARCHAR(10) NOT NULL,
	NOMBRES VARCHAR(200) NOT NULL,
	APPATERNO VARCHAR(200) NOT NULL,
	COSTO INT NULL,
	COSTOUSO INT NULL,
	APMATERNO VARCHAR(200) NOT NULL
);

CREATE TABLE PROYECTO(
	IDPROYECTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMPROYECTO VARCHAR(1024) NOT NULL,
	FECHAINI DATE NOT NULL,
	IDCLIENTE INT NOT NULL,
	IDJP INT NOT NULL
);

ALTER TABLE PROYECTO ADD FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE);
ALTER TABLE PROYECTO ADD FOREIGN KEY(IDJP) REFERENCES RECURSO(IDRECURSO);

CREATE TABLE ETAPAPROYECTO(
	IDETAPAPROYECTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDETAPA INT NOT NULL,
	IDPROYECTO INT NOT NULL
);

ALTER TABLE ETAPAPROYECTO ADD FOREIGN KEY(IDETAPA) REFERENCES ETAPA(IDETAPA);
ALTER TABLE ETAPAPROYECTO ADD FOREIGN KEY(IDPROYECTO) REFERENCES PROYECTO(IDPROYECTO);

CREATE TABLE ETAPAPROYECTOPERSONAL(
	IDETAPAPROYECTOPERSONAL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	IDRECURSO INT NOT NULL,
	PORCUSO INT NOT NULL,
	IDROL INT NOT NULL,
	IDETAPAPROYECTO INT NOT NULL
);

ALTER TABLE ETAPAPROYECTOPERSONAL ADD FOREIGN KEY(IDRECURSO) REFERENCES RECURSO(IDRECURSO);
ALTER TABLE ETAPAPROYECTOPERSONAL ADD FOREIGN KEY(IDROL) REFERENCES ROL(IDROL);
ALTER TABLE ETAPAPROYECTOPERSONAL ADD FOREIGN KEY(IDETAPAPROYECTO) REFERENCES ETAPAPROYECTO(IDETAPAPROYECTO);

